# _pages/admin_analytics_dashboard.py

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime, timedelta
from database.unified_db_manager import db
from modules.rbac import is_admin, render_role_badge

def show():
    """System Admin Analytics Dashboard - Complete metrics and KPIs"""
    
    # Verify admin access
    if not is_admin():
        st.error("🔒 Access denied. System admin privileges required.")
        return
    
    st.markdown("""
    <div class="main-header">
        <h1>📊 System Admin Analytics Dashboard</h1>
        <p>Complete platform metrics, AI value generation, and company performance</p>
    </div>
    """, unsafe_allow_html=True)
    
    render_role_badge()
    
    # Refresh button
    col1, col2, col3 = st.columns([1, 1, 4])
    with col1:
        if st.button("🔄 Refresh Data", use_container_width=True):
            st.cache_data.clear()
            st.rerun()
    
    st.markdown("---")
    
    # =========================================================================
    # SECTION 1: SAAS GROWTH METRICS (Top KPIs)
    # =========================================================================
    st.markdown("## 📈 SaaS Growth Metrics")
    
    growth_metrics = get_growth_metrics()
    
    col1, col2, col3, col4, col5 = st.columns(5)
    
    with col1:
        st.metric(
            "Total Tenants", 
            growth_metrics['total_tenants'],
            delta=f"+{growth_metrics['new_tenants_this_month']} this month"
        )
    with col2:
        st.metric(
            "Active Tenants (30d)", 
            growth_metrics['active_tenants'],
            delta=f"{growth_metrics['active_rate']:.1f}% of total"
        )
    with col3:
        st.metric(
            "New Tenants (MTD)", 
            growth_metrics['new_tenants_this_month'],
            delta=f"{growth_metrics['tenant_growth_rate']:+.1f}% MoM"
        )
    with col4:
        st.metric(
            "Monthly Revenue", 
            f"BDT {growth_metrics['monthly_revenue']:,.0f}",
            delta=f"{growth_metrics['revenue_growth']:+.1f}%"
        )
    with col5:
        st.metric(
            "Annual Revenue (ARR)", 
            f"BDT {growth_metrics['annual_revenue']:,.0f}",
            help="Annual Recurring Revenue"
        )
    
    # Charts
    col1, col2 = st.columns(2)
    
    with col1:
        render_tenant_growth_chart()
    
    with col2:
        render_revenue_growth_chart()
    
    st.markdown("---")
    
    # =========================================================================
    # SECTION 2: AI VALUE METRICS (Investor KPIs)
    # =========================================================================
    st.markdown("## 🤖 AI Value Generation")
    st.caption("These metrics demonstrate the value delivered by TenderAI")
    
    ai_metrics = get_ai_value_metrics()
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric(
            "💡 Manual Hours Saved",
            f"{ai_metrics['hours_saved']:,.0f} hrs",
            help="Total manual hours saved by using AI auto-fill"
        )
    with col2:
        st.metric(
            "💰 Cost Savings",
            f"BDT {ai_metrics['cost_savings']:,.0f}",
            help="Estimated cost savings from reduced manual work"
        )
    with col3:
        st.metric(
            "⚡ Decision Acceleration",
            f"{ai_metrics['acceleration_factor']:.1f}x",
            help="How much faster decisions are made with AI"
        )
    with col4:
        st.metric(
            "📊 AI Value Generated",
            f"BDT {ai_metrics['total_ai_value']:,.0f}",
            help="Total economic value generated by AI"
        )
    
    # AI Value Trend
    render_ai_value_trend()
    
    col1, col2 = st.columns(2)
    
    with col1:
        render_tender_volume_chart()
    
    with col2:
        render_ai_time_savings_chart()
    
    st.markdown("---")
    
    # =========================================================================
    # SECTION 3: PRODUCT USAGE METRICS
    # =========================================================================
    st.markdown("## 📊 Product Usage Metrics")
    
    usage_metrics = get_product_usage_metrics()
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric(
            "Total Tenders Uploaded",
            f"{usage_metrics['total_tenders']:,}"
        )
    with col2:
        st.metric(
            "Total Analyses Run",
            f"{usage_metrics['total_analyses']:,}"
        )
    with col3:
        st.metric(
            "Avg Analysis Time Saved",
            f"{usage_metrics['time_saved_per_analysis']:.0f}%",
            help="Time saved vs manual analysis"
        )
    with col4:
        st.metric(
            "Total Scenarios Generated",
            f"{usage_metrics['total_scenarios']:,}"
        )
    
    # Additional usage metrics
    col1, col2 = st.columns(2)
    
    with col1:
        st.metric(
            "Avg Scenarios per Tender",
            f"{usage_metrics['avg_scenarios_per_tender']:.1f}"
        )
    with col2:
        st.metric(
            "Active Users (30d)",
            f"{usage_metrics['active_users']:,}"
        )
    
    st.markdown("---")
    
    # =========================================================================
    # SECTION 4: COMPANY PERFORMANCE TABLES
    # =========================================================================
    st.markdown("## 🏢 Company Performance")
    
    tab1, tab2, tab3, tab4 = st.tabs([
        "🏆 Top Companies by Usage",
        "📋 Recent Tenants",
        "🔄 Active vs Inactive",
        "📊 Company Details"
    ])
    
    with tab1:
        render_top_companies_table()
    
    with tab2:
        render_recent_tenants_table()
    
    with tab3:
        render_active_inactive_chart()
    
    with tab4:
        render_company_details_table()


def get_growth_metrics():
    """Get SaaS growth metrics"""
    conn = db.get_connection()
    cursor = conn.cursor()
    
    # Total tenants
    cursor.execute("SELECT COUNT(*) FROM companies WHERE is_active = 1")
    total_tenants = cursor.fetchone()[0] or 0
    
    # Active tenants (last 30 days)
    thirty_days_ago = (datetime.now() - timedelta(days=30)).strftime('%Y-%m-%d')
    cursor.execute("""
        SELECT COUNT(DISTINCT company_id) 
        FROM users 
        WHERE last_login >= ? AND is_active = 1
    """, (thirty_days_ago,))
    active_tenants = cursor.fetchone()[0] or 0
    
    # New tenants this month
    start_of_month = datetime.now().replace(day=1).strftime('%Y-%m-%d')
    cursor.execute("""
        SELECT COUNT(*) FROM companies 
        WHERE created_at >= ? AND is_active = 1
    """, (start_of_month,))
    new_tenants = cursor.fetchone()[0] or 0
    
    # Previous month new tenants (for growth rate)
    last_month = datetime.now().replace(day=1) - timedelta(days=1)
    last_month_start = last_month.replace(day=1).strftime('%Y-%m-%d')
    cursor.execute("""
        SELECT COUNT(*) FROM companies 
        WHERE created_at >= ? AND created_at < ? AND is_active = 1
    """, (last_month_start, start_of_month))
    last_month_new = cursor.fetchone()[0] or 1  # Avoid division by zero
    
    tenant_growth_rate = ((new_tenants - last_month_new) / last_month_new) * 100
    
    # Monthly revenue from subscriptions
    cursor.execute("""
        SELECT 
            SUM(CASE 
                WHEN plan = 'basic' THEN 4999
                WHEN plan = 'professional' THEN 14999
                WHEN plan = 'enterprise' THEN 49999
                ELSE 0
            END) as revenue
        FROM subscriptions 
        WHERE status = 'active'
    """)
    monthly_revenue = cursor.fetchone()[0] or 0
    
    # Previous month revenue for growth
    cursor.execute("""
        SELECT 
            SUM(CASE 
                WHEN plan = 'basic' THEN 4999
                WHEN plan = 'professional' THEN 14999
                WHEN plan = 'enterprise' THEN 49999
                ELSE 0
            END) as revenue
        FROM subscriptions 
        WHERE status = 'active' AND created_at < ?
    """, (start_of_month,))
    prev_month_revenue = cursor.fetchone()[0] or 1
    
    revenue_growth = ((monthly_revenue - prev_month_revenue) / prev_month_revenue) * 100
    
    conn.close()
    
    return {
        'total_tenants': total_tenants,
        'active_tenants': active_tenants,
        'active_rate': (active_tenants / total_tenants * 100) if total_tenants > 0 else 0,
        'new_tenants_this_month': new_tenants,
        'tenant_growth_rate': tenant_growth_rate,
        'monthly_revenue': monthly_revenue,
        'annual_revenue': monthly_revenue * 12,
        'revenue_growth': revenue_growth
    }


def get_ai_value_metrics():
    """Calculate AI value generation metrics"""
    conn = db.get_connection()
    cursor = conn.cursor()
    
    # Get total analyses
    cursor.execute("SELECT COUNT(*) FROM tender_analyses")
    total_analyses = cursor.fetchone()[0] or 0
    
    # Get total extension auto-fills
    cursor.execute("SELECT COUNT(*) FROM extension_auto_fill_log")
    total_auto_fills = cursor.fetchone()[0] or 0
    
    # Average manual time per tender (minutes) - assumed industry standard
    manual_time_per_tender = 45  # minutes
    
    # AI time per tender (minutes) - based on auto-fill
    ai_time_per_tender = 5  # minutes
    
    # Time saved per tender
    time_saved_per_tender = manual_time_per_tender - ai_time_per_tender
    
    # Total hours saved
    total_hours_saved = (time_saved_per_tender * total_analyses) / 60
    
    # Add auto-fill time savings
    auto_fill_time_saved = total_auto_fills * 2 / 60  # 2 minutes per field saved
    total_hours_saved += auto_fill_time_saved
    
    # Estimated cost savings (assuming BDT 500 per hour average staff cost)
    hourly_rate = 500  # BDT per hour
    cost_savings = total_hours_saved * hourly_rate
    
    # Decision acceleration factor
    acceleration_factor = manual_time_per_tender / ai_time_per_tender
    
    # Total AI value generated (cost savings + efficiency gains)
    total_ai_value = cost_savings + (total_hours_saved * 200)  # 200 BDT per hour efficiency value
    
    conn.close()
    
    return {
        'hours_saved': total_hours_saved,
        'cost_savings': cost_savings,
        'acceleration_factor': acceleration_factor,
        'total_ai_value': total_ai_value
    }


def get_product_usage_metrics():
    """Get product usage statistics"""
    conn = db.get_connection()
    cursor = conn.cursor()
    
    # Total tenders
    cursor.execute("SELECT COUNT(*) FROM company_tenders WHERE is_active = 1")
    total_tenders = cursor.fetchone()[0] or 0
    
    # Total analyses
    cursor.execute("SELECT COUNT(*) FROM tender_analyses")
    total_analyses = cursor.fetchone()[0] or 0
    
    # Total scenarios
    cursor.execute("SELECT COUNT(*) FROM saved_scenarios")
    total_scenarios = cursor.fetchone()[0] or 0
    
    # Average scenarios per tender
    avg_scenarios = total_scenarios / total_tenders if total_tenders > 0 else 0
    
    # Active users (last 30 days)
    thirty_days_ago = (datetime.now() - timedelta(days=30)).strftime('%Y-%m-%d')
    cursor.execute("""
        SELECT COUNT(DISTINCT user_id) FROM extension_auto_fill_log 
        WHERE filled_at >= ?
    """, (thirty_days_ago,))
    active_users = cursor.fetchone()[0] or 0
    
    # Also include users from tender_analyses
    cursor.execute("""
        SELECT COUNT(DISTINCT user_id) FROM tender_analyses 
        WHERE analysis_date >= ?
    """, (thirty_days_ago,))
    analysis_users = cursor.fetchone()[0] or 0
    
    active_users = max(active_users, analysis_users)
    
    conn.close()
    
    return {
        'total_tenders': total_tenders,
        'total_analyses': total_analyses,
        'total_scenarios': total_scenarios,
        'avg_scenarios_per_tender': avg_scenarios,
        'active_users': active_users,
        'time_saved_per_analysis': 85  # Estimated 85% time saved
    }


def render_tenant_growth_chart():
    """Render tenant growth line chart"""
    conn = db.get_connection()
    
    # Get monthly tenant growth
    query = """
        SELECT 
            strftime('%Y-%m', created_at) as month,
            COUNT(*) as new_tenants,
            SUM(COUNT(*)) OVER (ORDER BY strftime('%Y-%m', created_at)) as cumulative
        FROM companies
        WHERE is_active = 1
        GROUP BY strftime('%Y-%m', created_at)
        ORDER BY month
        LIMIT 12
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        fig = go.Figure()
        
        fig.add_trace(go.Scatter(
            x=df['month'],
            y=df['cumulative'],
            mode='lines+markers',
            name='Total Tenants',
            line=dict(color='#667eea', width=3),
            marker=dict(size=8, color='#764ba2'),
            fill='tozeroy',
            fillcolor='rgba(102, 126, 234, 0.1)'
        ))
        
        fig.update_layout(
            title="Tenant Growth",
            xaxis_title="Month",
            yaxis_title="Number of Tenants",
            height=350,
            template="plotly_white"
        )
        
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("No tenant growth data available")


def render_revenue_growth_chart():
    """Render revenue growth line chart"""
    conn = db.get_connection()
    
    # Get monthly revenue
    query = """
        SELECT 
            strftime('%Y-%m', created_at) as month,
            SUM(CASE 
                WHEN plan = 'basic' THEN 4999
                WHEN plan = 'professional' THEN 14999
                WHEN plan = 'enterprise' THEN 49999
                ELSE 0
            END) as revenue
        FROM subscriptions
        WHERE status = 'active'
        GROUP BY strftime('%Y-%m', created_at)
        ORDER BY month
        LIMIT 12
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        fig = go.Figure()
        
        fig.add_trace(go.Bar(
            x=df['month'],
            y=df['revenue'],
            name='Monthly Revenue',
            marker_color='#10b981',
            text=df['revenue'].apply(lambda x: f'BDT {x:,.0f}'),
            textposition='auto'
        ))
        
        fig.update_layout(
            title="Monthly Revenue (BDT)",
            xaxis_title="Month",
            yaxis_title="Revenue (BDT)",
            height=350,
            template="plotly_white"
        )
        
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("No revenue data available")


def render_tender_volume_chart():
    """Render tender volume bar chart"""
    conn = db.get_connection()
    
    query = """
        SELECT 
            strftime('%Y-%m', created_at) as month,
            COUNT(*) as tenders
        FROM company_tenders
        WHERE is_active = 1
        GROUP BY strftime('%Y-%m', created_at)
        ORDER BY month
        LIMIT 12
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        fig = go.Figure()
        
        fig.add_trace(go.Bar(
            x=df['month'],
            y=df['tenders'],
            name='Tenders',
            marker_color='#f59e0b',
            text=df['tenders'],
            textposition='auto'
        ))
        
        fig.update_layout(
            title="Tender Volume Trend",
            xaxis_title="Month",
            yaxis_title="Number of Tenders",
            height=350,
            template="plotly_white"
        )
        
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("No tender volume data available")


def render_ai_time_savings_chart():
    """Render AI time savings area chart"""
    conn = db.get_connection()
    
    query = """
        SELECT 
            strftime('%Y-%m', analysis_date) as month,
            COUNT(*) as analyses
        FROM tender_analyses
        GROUP BY strftime('%Y-%m', analysis_date)
        ORDER BY month
        LIMIT 12
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        # Calculate estimated time savings (45 min manual - 5 min AI = 40 min saved)
        df['hours_saved'] = df['analyses'] * 40 / 60
        
        fig = go.Figure()
        
        fig.add_trace(go.Scatter(
            x=df['month'],
            y=df['hours_saved'],
            mode='lines',
            name='Hours Saved',
            line=dict(color='#ef4444', width=3),
            fill='tozeroy',
            fillcolor='rgba(239, 68, 68, 0.2)'
        ))
        
        fig.update_layout(
            title="AI Time Savings (Hours)",
            xaxis_title="Month",
            yaxis_title="Hours Saved",
            height=350,
            template="plotly_white"
        )
        
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("No AI time savings data available")


def render_ai_value_trend():
    """Render AI value generation trend"""
    conn = db.get_connection()
    
    query = """
        SELECT 
            strftime('%Y-%m', analysis_date) as month,
            COUNT(*) * 40 / 60 as hours_saved
        FROM tender_analyses
        GROUP BY strftime('%Y-%m', analysis_date)
        ORDER BY month
        LIMIT 12
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        df['cost_savings'] = df['hours_saved'] * 500  # BDT 500/hour
        df['ai_value'] = df['cost_savings'] + (df['hours_saved'] * 200)  # Total AI value
        
        fig = go.Figure()
        
        fig.add_trace(go.Bar(
            x=df['month'],
            y=df['cost_savings'],
            name='Cost Savings (BDT)',
            marker_color='#10b981'
        ))
        
        fig.add_trace(go.Scatter(
            x=df['month'],
            y=df['ai_value'],
            name='Total AI Value (BDT)',
            line=dict(color='#667eea', width=3),
            yaxis='y2'
        ))
        
        fig.update_layout(
            title="AI Value Generation Trend",
            xaxis_title="Month",
            yaxis_title="Cost Savings (BDT)",
            yaxis2=dict(
                title="Total AI Value (BDT)",
                overlaying='y',
                side='right'
            ),
            height=350,
            template="plotly_white"
        )
        
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("No AI value trend data available")


def render_top_companies_table():
    """Render top 10 companies by usage"""
    conn = db.get_connection()
    
    query = """
        SELECT 
            c.company_name,
            COUNT(DISTINCT ct.id) as tenders,
            COUNT(DISTINCT ta.id) as analyses,
            COUNT(DISTINCT e.id) as extension_uses,
            u.plan as subscription_plan,
            c.created_at as joined_date
        FROM companies c
        LEFT JOIN company_tenders ct ON c.id = ct.company_id AND ct.is_active = 1
        LEFT JOIN tender_analyses ta ON c.id = ta.company_id
        LEFT JOIN extension_auto_fill_log e ON c.id = e.company_id
        LEFT JOIN subscriptions u ON c.id = u.company_id
        WHERE c.is_active = 1
        GROUP BY c.id
        ORDER BY tenders DESC, analyses DESC
        LIMIT 10
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        # Format for display
        df['joined_date'] = pd.to_datetime(df['joined_date']).dt.strftime('%Y-%m-%d')
        df['subscription_plan'] = df['subscription_plan'].fillna('free').str.upper()
        
        st.dataframe(
            df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "company_name": "Company Name",
                "tenders": st.column_config.NumberColumn("Tenders"),
                "analyses": st.column_config.NumberColumn("Analyses"),
                "extension_uses": st.column_config.NumberColumn("Extension Uses"),
                "subscription_plan": "Plan",
                "joined_date": "Joined Date"
            }
        )
    else:
        st.info("No company data available")


def render_recent_tenants_table():
    """Render recent tenants"""
    conn = db.get_connection()
    
    query = """
        SELECT 
            company_name,
            email,
            phone,
            division,
            created_at as joined_date,
            (SELECT COUNT(*) FROM users WHERE company_id = companies.id) as user_count,
            (SELECT plan FROM subscriptions WHERE company_id = companies.id LIMIT 1) as plan
        FROM companies
        WHERE is_active = 1
        ORDER BY created_at DESC
        LIMIT 20
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        df['joined_date'] = pd.to_datetime(df['joined_date']).dt.strftime('%Y-%m-%d')
        df['plan'] = df['plan'].fillna('free').str.upper()
        
        st.dataframe(
            df,
            use_container_width=True,
            hide_index=True
        )
    else:
        st.info("No recent tenants found")


def render_active_inactive_chart():
    """Render active vs inactive tenants chart"""
    conn = db.get_connection()
    cursor = conn.cursor()
    
    thirty_days_ago = (datetime.now() - timedelta(days=30)).strftime('%Y-%m-%d')
    
    cursor.execute("""
        SELECT 
            COUNT(CASE WHEN last_login >= ? THEN 1 END) as active,
            COUNT(CASE WHEN last_login < ? OR last_login IS NULL THEN 1 END) as inactive
        FROM users 
        WHERE is_active = 1
    """, (thirty_days_ago, thirty_days_ago))
    
    result = cursor.fetchone()
    conn.close()
    
    active = result[0] or 0
    inactive = result[1] or 0
    
    fig = go.Figure(data=[go.Pie(
        labels=['Active (last 30 days)', 'Inactive'],
        values=[active, inactive],
        marker_colors=['#10b981', '#ef4444'],
        hole=0.4,
        textinfo='label+percent',
        textposition='auto'
    )])
    
    fig.update_layout(
        title="User Activity Status",
        height=350,
        annotations=[dict(text=f"Total: {active + inactive}", x=0.5, y=0.5, font_size=20, showarrow=False)]
    )
    
    st.plotly_chart(fig, use_container_width=True)


def render_company_details_table():
    """Render detailed company performance table"""
    conn = db.get_connection()
    
    query = """
        SELECT 
            c.company_name,
            c.email,
            c.division,
            c.created_at,
            COUNT(DISTINCT u.id) as total_users,
            COUNT(DISTINCT ct.id) as total_tenders,
            COUNT(DISTINCT ta.id) as total_analyses,
            COUNT(DISTINCT e.id) as extension_uses,
            COALESCE((
                SELECT SUM(CASE 
                    WHEN plan = 'basic' THEN 4999
                    WHEN plan = 'professional' THEN 14999
                    WHEN plan = 'enterprise' THEN 49999
                    ELSE 0
                END) 
                FROM subscriptions 
                WHERE company_id = c.id AND status = 'active'
            ), 0) as monthly_revenue
        FROM companies c
        LEFT JOIN users u ON c.id = u.company_id AND u.is_active = 1
        LEFT JOIN company_tenders ct ON c.id = ct.company_id AND ct.is_active = 1
        LEFT JOIN tender_analyses ta ON c.id = ta.company_id
        LEFT JOIN extension_auto_fill_log e ON c.id = e.company_id
        WHERE c.is_active = 1
        GROUP BY c.id
        ORDER BY total_analyses DESC
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    if not df.empty:
        # Calculate retention rate (simplified)
        df['retention_rate'] = df.apply(lambda x: 
            min(100, (x['extension_uses'] / max(x['total_analyses'], 1)) * 100), axis=1
        )
        
        # Format for display
        df['created_at'] = pd.to_datetime(df['created_at']).dt.strftime('%Y-%m-%d')
        df['retention_rate'] = df['retention_rate'].apply(lambda x: f"{x:.1f}%")
        
        st.dataframe(
            df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "company_name": "Company",
                "email": "Email",
                "division": "Division",
                "created_at": "Joined",
                "total_users": st.column_config.NumberColumn("Users"),
                "total_tenders": st.column_config.NumberColumn("Tenders"),
                "total_analyses": st.column_config.NumberColumn("Analyses"),
                "extension_uses": st.column_config.NumberColumn("Extension"),
                "monthly_revenue": st.column_config.NumberColumn("Monthly Revenue", format="BDT %.0f"),
                "retention_rate": "Retention"
            }
        )
        
        # Download option
        csv = df.to_csv(index=False)
        st.download_button(
            "📥 Download Company Data (CSV)",
            csv,
            f"company_performance_{datetime.now().strftime('%Y%m%d')}.csv",
            "text/csv"
        )
    else:
        st.info("No company data available")