"""
MISSING METHODS TO ADD TO crud_operations.py
Auto-generated from old db_manager.py files
Generated by: migrations/copy_missing_methods.py
"""

import logging
from typing import Optional, Dict, List, Any
from datetime import datetime, timedelta
import json

logger = logging.getLogger(__name__)


# =========================================================
# METHOD: add_lged_chapter
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def add_lged_chapter(self, chapter_number, chapter_name, description=""):
        """Add a new LGED chapter"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute("""
            INSERT OR REPLACE INTO lged_chapters (chapter_number, chapter_name, description)
            VALUES (?, ?, ?)
        """, (chapter_number, chapter_name, description))
        conn.commit()
        conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: add_pwd_chapter
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def add_pwd_chapter(self, chapter_number, chapter_name, description=""):
        """Add a new PWD chapter"""
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute("""
            INSERT OR REPLACE INTO pwd_chapters (chapter_number, chapter_name, description)
            VALUES (?, ?, ?)
        """, (chapter_number, chapter_name, description))
        conn.commit()
        conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: clear_lged_version_data
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def clear_lged_version_data(self, version_id):
        """Clear all LGED data for a specific version"""
        try:
            conn = self.get_connection()
            cursor = conn.cursor()
            
            # Delete in correct order (child tables first due to foreign keys)
            cursor.execute("DELETE FROM lged_zone_rates WHERE version_id = ?", (version_id,))
            cursor.execute("DELETE FROM lged_children WHERE version_id = ?", (version_id,))
            cursor.execute("DELETE FROM lged_parents WHERE version_id = ?", (version_id,))
            
            conn.commit()
            conn.close()
            print(f"✅ Cleared LGED data for version ID: {version_id}")
            return True
            
        except Exception as e:
            print(f"Error clearing LGED version data: {e}")
            return False
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: clear_pwd_version_data
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def clear_pwd_version_data(self, version_id):
        """Clear all PWD data for a specific version"""
        try:
            conn = self.get_connection()
            cursor = conn.cursor()
            
            # Delete in correct order (child tables first due to foreign keys)
            cursor.execute("DELETE FROM pwd_rates WHERE version_id = ?", (version_id,))
            cursor.execute("DELETE FROM pwd_children WHERE version_id = ?", (version_id,))
            cursor.execute("DELETE FROM pwd_parents WHERE version_id = ?", (version_id,))
            
            conn.commit()
            conn.close()
            print(f"✅ Cleared PWD data for version ID: {version_id}")
            return True
            
        except Exception as e:
            print(f"Error clearing PWD version data: {e}")
            return False
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: get_lged_sections_by_chapter
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def get_lged_sections_by_chapter(self, chapter_number: str) -> pd.DataFrame:
        """
        Get LGED sections for a specific chapter from rate_sections table.
        
        Args:
            chapter_number: The chapter number (e.g., "1", "2")
        
        Returns:
            DataFrame with sections
        """
        try:
            conn = self.get_connection()
            
            # First get the chapter ID
            cursor = conn.cursor()
            cursor.execute("""
                SELECT id FROM rate_chapters 
                WHERE source = 'LGED' AND chapter_number = ?
                ORDER BY id DESC LIMIT 1
            """, (chapter_number,))
            
            chapter_row = cursor.fetchone()
            
            if chapter_row:
                chapter_id = chapter_row[0]
                df = pd.read_sql_query("""
                    SELECT section_number, section_name, description
                    FROM rate_sections 
                    WHERE source = 'LGED' AND chapter_id = ?
                    ORDER BY section_number
                """, conn, params=[chapter_id])
            else:
                df = pd.DataFrame()
            
            conn.close()
            return df
            
        except Exception as e:
            logger.error(f"Error getting sections for chapter {chapter_number}: {e}")
            return pd.DataFrame()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: get_pwd_stats
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def get_pwd_stats(self):
        """Get PWD statistics"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        cursor.execute("SELECT COUNT(*) FROM pwd_parents")
        total_parents = cursor.fetchone()[0]
        
        cursor.execute("SELECT COUNT(*) FROM pwd_children")
        total_children = cursor.fetchone()[0]
        
        cursor.execute("SELECT COUNT(*) FROM pwd_rates")
        total_rates = cursor.fetchone()[0]
        
        conn.close()
        
        return {
            'total_parents': total_parents,
            'total_children': total_children,
            'total_rates': total_rates,
            'total_items': total_parents + total_children
        }
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: get_version_history
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def get_version_history(self, source: str, edition_year: int) -> pd.DataFrame:
        """Get version history for a specific source and edition year"""
        conn = self.get_connection()
        
        try:
            # Use a simpler query that works regardless of columns
            query = """
                SELECT 
                    id, 
                    version_name, 
                    version_number, 
                    is_active,
                    COALESCE(created_at, release_date, datetime('now')) as created_at,
                    COALESCE(updated_at, release_date, datetime('now')) as updated_at,
                    COALESCE(total_parents, 0) as total_parents,
                    COALESCE(total_children, 0) as total_children,
                    COALESCE(total_rates, 0) as total_rates,
                    COALESCE(notes, '') as notes
                FROM rate_versions
                WHERE source = ? AND edition_year = ?
                ORDER BY version_number DESC
            """
            
            df = pd.read_sql_query(query, conn, params=(source, edition_year))
            
            # Calculate total_items
            if not df.empty:
                df['total_items'] = df['total_parents'] + df['total_children']
            
            conn.close()
            return df
            
        except Exception as e:
            print(f"Error getting version history: {e}")
            conn.close()
            return pd.DataFrame()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: init_chapters_tables
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def init_chapters_tables(self):
        """Initialize chapters tables for both PWD and LGED"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # PWD Chapters table (without description column initially)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS pwd_chapters (
                chapter_number TEXT PRIMARY KEY,
                chapter_name TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Add description column if it doesn't exist (for future use)
        try:
            cursor.execute("ALTER TABLE pwd_chapters ADD COLUMN description TEXT")
        except sqlite3.OperationalError:
            pass  # Column already exists
        
        # LGED Chapters table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS lged_chapters (
                chapter_number TEXT PRIMARY KEY,
                chapter_name TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        
        # Add description column if it doesn't exist
        try:
            cursor.execute("ALTER TABLE lged_chapters ADD COLUMN description TEXT")
        except sqlite3.OperationalError:
            pass  # Column already exists
        
        # Insert default PWD chapters
        default_pwd_chapters = [
            ("01", "General, Site Facilities and Safety"),
            ("02", "Excavation, Filling & Site Development"),
            ("03", "Brick Works, Patent Stone and Fancy Screen"),
            ("04", "Reinforced Cement Concrete (RCC) Works"),
            ("05", "Mosaic Works"),
            ("06", "Tiles, Marble and Granite Stone Works"),
            ("07", "Wood Works"),
            ("08", "Window Grill, Verandah Grill & Netting"),
            ("09", "Pile Works and Pile Test"),
            ("10", "Structural Steel Works"),
            ("11", "Wood Works in Door and Window Frame"),
            ("12", "Collapsible Gate, M.S. Gate, Rolling Shutter"),
            ("13", "Aluminium Door, Window and Partition"),
            ("14", "Cement Plaster, Fair-Face Plaster"),
            ("15", "Painting and Polishing"),
            ("16", "Water Proofing and Heat Proofing"),
            ("17", "False Ceiling and Wall Panelling"),
            ("18", "Sanitary and Plumbing Works"),
            ("19", "Gas Pipe Line Installation"),
            ("20", "Sub-Soil Investigation"),
            ("21", "Repair Works")
        ]
        
        for chapter_num, chapter_name in default_pwd_chapters:
            cursor.execute("""
                INSERT OR IGNORE INTO pwd_chapters (chapter_number, chapter_name)
                VALUES (?, ?)
            """, (chapter_num, chapter_name))
        
        # Insert default LGED chapters
        default_lged_chapters = [
            ("1", "General, Site Facilities and Safety"),
            ("2", "Earth Works in Road Embankment"),
            ("3", "Sub-Base and Base Course"),
            ("4", "Bituminous Pavement"),
            ("5", "Bridge and Culvert Works"),
            ("6", "Building Works"),
            ("7", "Sanitary and Water Supply"),
            ("8", "Electrical Works"),
            ("9", "Landscaping and Development")
        ]
        
        for chapter_num, chapter_name in default_lged_chapters:
            cursor.execute("""
                INSERT OR IGNORE INTO lged_chapters (chapter_number, chapter_name)
                VALUES (?, ?)
            """, (chapter_num, chapter_name))
        
        conn.commit()
        conn.close()
        print("✅ Chapters tables initialized")
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: init_lged_tables
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def init_lged_tables(self):
        """Initialize LGED-specific tables"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # LGED Versions table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS rate_versions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source TEXT DEFAULT 'LGED',
                version_name TEXT NOT NULL,
                edition_year INTEGER NOT NULL,
                effective_from DATE,
                is_active BOOLEAN DEFAULT 0,
                released_by TEXT,
                release_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                notes TEXT,
                total_parents INTEGER DEFAULT 0,
                total_children INTEGER DEFAULT 0,
                total_rates INTEGER DEFAULT 0,
                created_by TEXT
            )
        """)
        
        # LGED Parents table (updated to support both section headers and leaf items)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS lged_parents (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                code TEXT NOT NULL,
                description TEXT,
                chapter_number TEXT,
                section_number TEXT,
                parent_type TEXT DEFAULT 'section_header',  -- 'section_header' or 'leaf_item'
                has_children BOOLEAN DEFAULT 0,
                unit TEXT,
                version_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (version_id) REFERENCES rate_versions(id)
            )
        """)
        
        # LGED Children table (for items that belong to section headers)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS lged_children (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                code TEXT NOT NULL,
                parent_code TEXT NOT NULL,
                description TEXT,
                unit TEXT,
                chapter_number TEXT,
                section_number TEXT,
                zone_a REAL,
                zone_b REAL,
                zone_c REAL,
                zone_d REAL,
                edition_year INTEGER,
                version_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (version_id) REFERENCES rate_versions(id)
            )
        """)
        
        # LGED Zone Rates table (for leaf items)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS lged_zone_rates (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                parent_id INTEGER,
                zone_name TEXT NOT NULL,
                unit_rate REAL NOT NULL,
                version_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (parent_id) REFERENCES lged_parents(id),
                FOREIGN KEY (version_id) REFERENCES rate_versions(id)
            )
        """)
        
        # LGED Sections table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS lged_sections (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                chapter_number TEXT NOT NULL,
                section_number TEXT NOT NULL,
                section_name TEXT NOT NULL,
                description TEXT,
                display_order INTEGER DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(chapter_number, section_number)
            )
        """)
        
        # Zone mapping table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS lged_zone_mapping (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                zone_code TEXT PRIMARY KEY,
                zone_name TEXT,
                divisions TEXT,
                accessibility_bonus REAL DEFAULT 0.05,
                description TEXT
            )
        """)
        
        # Insert default zone mapping
        cursor.execute("""
            INSERT OR IGNORE INTO lged_zone_mapping (zone_code, zone_name, divisions, accessibility_bonus)
            VALUES 
            ('A', 'Dhaka & Mymensingh Division', '["Dhaka","Mymensingh"]', 0.05),
            ('B', 'Chattogram & Sylhet Division', '["Chattogram","Sylhet"]', 0.05),
            ('C', 'Rajshahi & Rangpur Division', '["Rajshahi","Rangpur"]', 0.05),
            ('D', 'Khulna & Barishal Division', '["Khulna","Barishal"]', 0.05)
        """)
        
        # Insert default sections for Chapter 1 (your data uses Chapter 1)
        default_sections = [
            ("1", "1.01", "Site Office Setup", 1),
            ("1", "1.1", "Videography Services", 2),
        ]
        
        for chapter_num, section_num, section_name, display_order in default_sections:
            cursor.execute("""
                INSERT OR IGNORE INTO lged_sections (chapter_number, section_number, section_name, display_order)
                VALUES (?, ?, ?, ?)
            """, (chapter_num, section_num, section_name, display_order))
        
        conn.commit()
        conn.close()
        print("✅ LGED tables initialized")
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: init_pwd_hierarchical_tables
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def init_pwd_hierarchical_tables(self):
        """Initialize hierarchical PWD tables"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # Ensure rate_versions table exists with all columns
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS rate_versions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source TEXT DEFAULT 'PWD',
                version_name TEXT NOT NULL,
                edition_year INTEGER NOT NULL,
                effective_from DATE,
                is_active BOOLEAN DEFAULT 0,
                released_by TEXT,
                release_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                notes TEXT,
                total_parents INTEGER DEFAULT 0,
                total_children INTEGER DEFAULT 0,
                total_rates INTEGER DEFAULT 0,
                created_by TEXT
            )
        """)
        
        # Parent items table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS pwd_parents (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                pwd_code TEXT PRIMARY KEY,
                description TEXT,
                chapter_number TEXT,
                version_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        # Child items table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS pwd_children (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                pwd_code TEXT PRIMARY KEY,
                parent_code TEXT NOT NULL,
                description TEXT,
                unit TEXT,
                edition_year INTEGER,
                version_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (parent_code) REFERENCES pwd_parents(pwd_code) ON DELETE CASCADE
            )
        ''')
        
        # Rates table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS pwd_rates (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                pwd_code TEXT NOT NULL,
                zone_name TEXT NOT NULL,
                unit_rate REAL NOT NULL,
                edition_year INTEGER NOT NULL,
                version_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(pwd_code, zone_name, edition_year),
                FOREIGN KEY (pwd_code) REFERENCES pwd_children(pwd_code) ON DELETE CASCADE
            )
        ''')
        
        # Indexes
        cursor.execute('CREATE INDEX IF NOT EXISTS idx_pwd_parent_chapter ON pwd_parents(chapter_number)')
        cursor.execute('CREATE INDEX IF NOT EXISTS idx_pwd_child_parent ON pwd_children(parent_code)')
        cursor.execute('CREATE INDEX IF NOT EXISTS idx_pwd_rates_code ON pwd_rates(pwd_code)')
        
        conn.commit()
        conn.close()
        print("✅ PWD hierarchical tables initialized")
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: migrate_lged_tables_for_parent_types
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def migrate_lged_tables_for_parent_types(self):
        """Migrate existing LGED tables to support parent types (section_header vs leaf_item)"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # Check and add parent_type column to lged_parents
        cursor.execute("PRAGMA table_info(lged_parents)")
        columns = [col[1] for col in cursor.fetchall()]
        
        if 'parent_type' not in columns:
            cursor.execute("ALTER TABLE lged_parents ADD COLUMN parent_type TEXT DEFAULT 'section_header'")
            print("✅ Added parent_type to lged_parents")
        
        if 'has_children' not in columns:
            cursor.execute("ALTER TABLE lged_parents ADD COLUMN has_children BOOLEAN DEFAULT 0")
            print("✅ Added has_children to lged_parents")
        
        if 'unit' not in columns:
            cursor.execute("ALTER TABLE lged_parents ADD COLUMN unit TEXT")
            print("✅ Added unit to lged_parents")
        
        # Check lged_children for rate columns
        cursor.execute("PRAGMA table_info(lged_children)")
        child_columns = [col[1] for col in cursor.fetchall()]
        
        if 'zone_a' not in child_columns:
            cursor.execute("ALTER TABLE lged_children ADD COLUMN zone_a REAL")
            cursor.execute("ALTER TABLE lged_children ADD COLUMN zone_b REAL")
            cursor.execute("ALTER TABLE lged_children ADD COLUMN zone_c REAL")
            cursor.execute("ALTER TABLE lged_children ADD COLUMN zone_d REAL")
            print("✅ Added zone rate columns to lged_children")
        
        conn.commit()
        conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: search_pwd_items
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def search_pwd_items(self, search_term, limit=50):
        """Search PWD items by code or description"""
        conn = self.get_connection()
        df = pd.read_sql_query("""
            SELECT pwd_code, description, unit 
            FROM pwd_children 
            WHERE pwd_code LIKE ? OR description LIKE ?
            LIMIT ?
        """, conn, params=(f"%{search_term}%", f"%{search_term}%", limit))
        conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: update_company_subscription
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def update_company_subscription(self, company_id, plan, duration='monthly', payment_method='admin', transaction_id=None):
        """Update or create subscription for a company"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        start_date = datetime.now().date()
        
        # Plan limits and pricing
        plan_limits = {
            'free': {'limit': 5, 'price': 0},
            'basic': {'limit': 30, 'price': 4999},
            'professional': {'limit': -1, 'price': 14999},
            'enterprise': {'limit': -1, 'price': 49999}
        }
        
        if duration == 'monthly':
            end_date = start_date + timedelta(days=30)
        else:
            end_date = start_date + timedelta(days=365)
        
        # Check if subscription exists
        cursor.execute('SELECT id FROM subscriptions WHERE company_id = ? AND company_id IS NOT NULL', (company_id,))
        existing = cursor.fetchone()
        
        if existing:
            cursor.execute('''
                UPDATE subscriptions 
                SET plan = ?, status = 'active', start_date = ?, end_date = ?, 
                    analyses_limit = ?, payment_method = ?, transaction_id = ?, updated_at = ?
                WHERE company_id = ?
            ''', (plan, start_date, end_date, plan_limits[plan]['limit'], 
                payment_method, transaction_id or f"ADMIN_{datetime.now().strftime('%Y%m%d%H%M%S')}", 
                datetime.now(), company_id))
        else:
            cursor.execute('''
                INSERT INTO subscriptions (company_id, plan, status, start_date, end_date, 
                                        analyses_limit, payment_method, transaction_id)
                VALUES (?, ?, 'active', ?, ?, ?, ?, ?)
            ''', (company_id, plan, start_date, end_date, plan_limits[plan]['limit'], 
                payment_method, transaction_id or f"ADMIN_{datetime.now().strftime('%Y%m%d%H%M%S')}"))
        
        conn.commit()
        conn.close()
        return True
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: update_competitor_master
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def update_competitor_master(self, competitor_id, update_data):
        """Update competitor information"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        fields = []
        values = []
        for key, value in update_data.items():
            fields.append(f"{key} = ?")
            values.append(value)
        
        values.append(competitor_id)
        query = f"UPDATE competitor_master SET {', '.join(fields)}, updated_at = ? WHERE id = ?"
        values.insert(0, datetime.now())
        
        cursor.execute(query, values)
        conn.commit()
        conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: update_historical_tender_schema
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def update_historical_tender_schema(self):
        """Add new columns for winner tracking if not exists"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # Add winning_company_type column
        try:
            cursor.execute("ALTER TABLE historical_tenders ADD COLUMN winning_company_type TEXT")
            print("✓ Added winning_company_type column")
        except sqlite3.OperationalError:
            pass  # Column already exists
        
        # Add our_awarded_price column
        try:
            cursor.execute("ALTER TABLE historical_tenders ADD COLUMN our_awarded_price REAL")
            print("✓ Added our_awarded_price column")
        except sqlite3.OperationalError:
            pass  # Column already exists
        
        conn.commit()
        conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: update_lged_chapter_section
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def update_lged_chapter_section(self, hierarchy, version_id, edition_year, 
                                  chapter_num, section_num=None, notes=None):
        """
        Update data for a specific chapter/section within an existing version.
        Only affects items belonging to the specified chapter/section.
        """
        conn = self.get_connection()
        cursor = conn.cursor()
        
        try:
            # Verify version exists
            cursor.execute("""
                SELECT id, version_number FROM rate_versions 
                WHERE id = ? AND source = 'LGED'
            """, (version_id,))
            
            version = cursor.fetchone()
            if not version:
                return {
                    'success': False,
                    'error': f"Version {version_id} not found",
                    'message': "Version not found"
                }
            
            version_number = version[1]
            
            # Get data from hierarchy
            section_headers = hierarchy.get('section_headers', [])
            rate_items = hierarchy.get('rate_items', [])
            
            # Delete existing data for this specific chapter/section
            if section_num:
                # Delete specific section within chapter
                cursor.execute("""
                    DELETE FROM lged_children 
                    WHERE version_id = ? AND chapter_number = ? AND section_number = ?
                """, (version_id, chapter_num, section_num))
                
                cursor.execute("""
                    DELETE FROM lged_parents 
                    WHERE version_id = ? AND chapter_number = ? AND section_number = ?
                """, (version_id, chapter_num, section_num))
            else:
                # Delete entire chapter
                cursor.execute("""
                    DELETE FROM lged_children 
                    WHERE version_id = ? AND chapter_number = ?
                """, (version_id, chapter_num))
                
                cursor.execute("""
                    DELETE FROM lged_parents 
                    WHERE version_id = ? AND chapter_number = ?
                """, (version_id, chapter_num))
            
            # Save section headers for this chapter/section
            for header in section_headers:
                cursor.execute("""
                    INSERT INTO lged_parents (code, description, chapter_number, section_number, 
                                            parent_type, has_children, version_id)
                    VALUES (?, ?, ?, ?, 'section_header', ?, ?)
                """, (header['code'], header.get('description', '')[:500], 
                    header.get('chapter_number', chapter_num), 
                    header.get('section_number', section_num or ''),
                    1 if header.get('has_children') else 0, version_id))
            
            # Save rate items for this chapter/section
            for item in rate_items:
                parent_code_val = item.get('parent_code') if item.get('parent_code') else None
                
                cursor.execute("""
                    INSERT INTO lged_children (
                        code, parent_code, description, unit, 
                        chapter_number, section_number,
                        zone_a, zone_b, zone_c, zone_d,
                        edition_year, version_id, is_parent
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    item['code'], 
                    parent_code_val,
                    item.get('description', '')[:500], 
                    item.get('unit', ''),
                    item.get('chapter_number', chapter_num), 
                    item.get('section_number', section_num or ''),
                    item.get('zone_a'), item.get('zone_b'), 
                    item.get('zone_c'), item.get('zone_d'),
                    edition_year, version_id, 
                    1 if item.get('is_parent') else 0
                ))
            
            # Update version statistics (recalculate totals)
            cursor.execute("""
                SELECT COUNT(*) FROM lged_parents WHERE version_id = ?
            """, (version_id,))
            total_parents = cursor.fetchone()[0]
            
            cursor.execute("""
                SELECT COUNT(*) FROM lged_children WHERE version_id = ?
            """, (version_id,))
            total_children = cursor.fetchone()[0]
            
            cursor.execute("""
                SELECT COUNT(*) FROM lged_children WHERE version_id = ?
            """, (version_id,))
            total_rate_items = cursor.fetchone()[0]
            total_rates = total_rate_items * 4
            
            cursor.execute("""
                UPDATE rate_versions 
                SET total_parents = ?, total_children = ?, total_rates = ?,
                    updated_at = ?, notes = ?
                WHERE id = ?
            """, (total_parents, total_children, total_rates, datetime.now(), notes, version_id))
            
            conn.commit()
            
            return {
                'success': True,
                'version_id': version_id,
                'version_number': version_number,
                'chapter': chapter_num,
                'section': section_num,
                'mode': 'update_chapter_section',
                'total_parents': total_parents,
                'total_children': total_children,
                'total_rates': total_rates,
                'message': f"✅ Updated Chapter {chapter_num}" + (f" Section {section_num}" if section_num else "") + f" in Version {version_number}"
            }
            
        except Exception as e:
            conn.rollback()
            import traceback
            traceback.print_exc()
            return {
                'success': False,
                'error': str(e),
                'mode': 'update_chapter_section',
                'message': f"❌ Failed to update: {e}"
            }
        finally:
            conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: update_lged_hierarchy
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def update_lged_hierarchy(self, hierarchy, edition_year, notes=None):
        """
        UPDATE existing active version (replaces data, no version increment)
        """
        from datetime import date
        
        self.migrate_lged_tables_for_parent_types()
        
        conn = self.get_connection()
        cursor = conn.cursor()
        
        try:
            # Get the active version
            cursor.execute("""
                SELECT id, version_number FROM rate_versions 
                WHERE source = 'LGED' AND edition_year = ? AND is_active = 1
            """, (edition_year,))
            
            result = cursor.fetchone()
            if not result:
                return {
                    'success': False,
                    'error': f"No active version found for LGED {edition_year}",
                    'mode': 'update_existing',
                    'message': f"❌ No active version found. Please do a first-time import first."
                }
            
            version_id = result[0]
            current_version = result[1]
            
            # Clear existing data for this version
            cursor.execute("DELETE FROM lged_zone_rates WHERE version_id = ?", (version_id,))
            cursor.execute("DELETE FROM lged_children WHERE version_id = ?", (version_id,))
            cursor.execute("DELETE FROM lged_parents WHERE version_id = ?", (version_id,))
            
            # Insert the new/updated data
            section_headers = hierarchy.get('section_headers', [])
            leaf_items = hierarchy.get('leaf_items', [])
            children = hierarchy.get('children', [])
            
            parent_ids = {}
            
            # Save section headers
            for header in section_headers:
                cursor.execute("""
                    INSERT INTO lged_parents (code, description, chapter_number, section_number, 
                                            parent_type, has_children, version_id)
                    VALUES (?, ?, ?, ?, 'section_header', ?, ?)
                """, (header['code'], header.get('description', ''), 
                    header.get('chapter_number', ''), header.get('section_number', ''),
                    1 if header.get('has_children') else 0, version_id))
                parent_ids[header['code']] = cursor.lastrowid
            
            # Save leaf items
            for leaf in leaf_items:
                cursor.execute("""
                    INSERT INTO lged_parents (code, description, chapter_number, section_number, 
                                            parent_type, has_children, unit, version_id)
                    VALUES (?, ?, ?, ?, 'leaf_item', 0, ?, ?)
                """, (leaf['code'], leaf.get('description', ''), 
                    leaf.get('chapter_number', ''), leaf.get('section_number', ''),
                    leaf.get('unit', ''), version_id))
                parent_id = cursor.lastrowid
                parent_ids[leaf['code']] = parent_id
                
                for zone, rate in leaf.get('rates', {}).items():
                    cursor.execute("""
                        INSERT INTO lged_zone_rates (parent_id, zone_name, unit_rate, version_id)
                        VALUES (?, ?, ?, ?)
                    """, (parent_id, zone, rate, version_id))
            
            # Save child items
            for child in children:
                cursor.execute("""
                    INSERT INTO lged_children (code, parent_code, description, unit, 
                                            chapter_number, section_number,
                                            zone_a, zone_b, zone_c, zone_d,
                                            edition_year, version_id)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (child['code'], child.get('parent_code', ''), child.get('description', ''), 
                    child.get('unit', ''),
                    child.get('chapter_number', ''), child.get('section_number', ''),
                    child.get('zone_a'), child.get('zone_b'), 
                    child.get('zone_c'), child.get('zone_d'),
                    edition_year, version_id))
            
            # Update version record
            cursor.execute("""
                UPDATE rate_versions 
                SET total_parents = ?, total_children = ?, total_rates = ?,
                    updated_at = ?, notes = ?
                WHERE id = ?
            """, (len(section_headers) + len(leaf_items), len(children), 
                len(leaf_items) + len(children),
                datetime.now(), notes or "Updated via import", version_id))
            
            conn.commit()
            
            return {
                'success': True,
                'version_id': version_id,
                'version_number': current_version,
                'mode': 'update_existing',
                'message': f"✅ Updated existing version {current_version} for LGED {edition_year}"
            }
            
        except Exception as e:
            conn.rollback()
            return {
                'success': False,
                'error': str(e),
                'mode': 'update_existing',
                'message': f"❌ Failed to update: {e}"
            }
        finally:
            conn.close()
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: update_role_permissions_for_rates
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def update_role_permissions_for_rates(self):
        """Add rate management permissions to role_permissions table"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # Define rate management permissions for each role
        rate_permissions = {
            'admin': {
                'manage_zones': True,
                'manage_chapters': True,
                'manage_parents': True,
                'manage_children': True,
                'manage_versions': True,
                'view_rates': True,
                'edit_rates': True,
                'delete_rates': True
            },
            'system_admin': {
                'manage_zones': True,
                'manage_chapters': True,
                'manage_parents': True,
                'manage_children': True,
                'manage_versions': True,
                'view_rates': True,
                'edit_rates': True,
                'delete_rates': True
            },
            'company_admin': {
                'manage_zones': False,  # Zones are system-wide
                'manage_chapters': True,
                'manage_parents': True,
                'manage_children': True,
                'manage_versions': True,
                'view_rates': True,
                'edit_rates': True,
                'delete_rates': False
            },
            'manager': {
                'manage_zones': False,
                'manage_chapters': True,
                'manage_parents': True,
                'manage_children': True,
                'manage_versions': False,
                'view_rates': True,
                'edit_rates': True,
                'delete_rates': False
            },
            'analyst': {
                'manage_zones': False,
                'manage_chapters': False,
                'manage_parents': False,
                'manage_children': True,
                'manage_versions': False,
                'view_rates': True,
                'edit_rates': True,
                'delete_rates': False
            },
            'data_entry': {
                'manage_zones': False,
                'manage_chapters': False,
                'manage_parents': True,
                'manage_children': True,
                'manage_versions': False,
                'view_rates': True,
                'edit_rates': True,
                'delete_rates': False
            },
            'viewer': {
                'manage_zones': False,
                'manage_chapters': False,
                'manage_parents': False,
                'manage_children': False,
                'manage_versions': False,
                'view_rates': True,
                'edit_rates': False,
                'delete_rates': False
            }
        }
        
        # Update each role's permissions
        for role, perms in rate_permissions.items():
            # Get existing permissions
            existing = self.get_role_permissions(role)
            # Merge with new permissions
            existing.update(perms)
            # Save back
            self.update_role_permissions(role, existing)
        
        print("✅ Rate management permissions added to roles")
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

# =========================================================
# METHOD: update_tender_lock_status
# Source: db_manager.py
# TODO: Refactor for unified database
# =========================================================

    # TODO: Refactor this method for unified DB
    # Source: db_manager.py
    def update_tender_lock_status(self, tender_id: int, locked: bool) -> bool:
        """Update the lock status of a tender"""
        try:
            conn = self.get_connection()
            cursor = conn.cursor()
            cursor.execute('''
            UPDATE company_tenders 
            SET is_locked = ?, locked_at = ?, locked_by = ?
            WHERE id = ?
            ''', (
                1 if locked else 0,
                datetime.now().strftime('%Y-%m-%d %H:%M:%S') if locked else None,
                st.session_state.user_id if locked else None,
                tender_id
            ))
            conn.commit()
            conn.close()
            return True
        except Exception as e:
            logger.error(f"Failed to update tender lock status: {e}")
            return False
    
    # REFACTORING NOTES:
    # 1. Change 'conn = self.get_connection()' to 'with self.get_connection() as conn:'
    # 2. Change 'cursor = conn.cursor()' to 'cursor = self.db_conn.get_cursor(conn)'
    # 3. Change 'row[0]' to 'row.get('column_name')'
    # 4. Remove explicit 'conn.close()' (context manager handles it)
    

