[server]
enableCORS = true
enableXsrfProtection = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
[logger]

# Level of logging for Streamlit's internal logger: "error", "warning", "info", or "debug"
level = "error"
