GOOGLE_CLIENT_ID  = "753240528860-979shi1o7rd7ob8145qld9mlpfeblmqk.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
redirect_uri = "http://localhost:8501/oauth2callback"

# For Streamlit Cloud: redirect_uri = "https://itender-bd.streamlit.app/"
